channels = ["huggingface", "pytorch"]

[deps]
git = ""
python = "3.9"
transformers = "4.25.1"

[pip.deps]
huggingface-hub = "@git+https://github.com/huggingface/huggingface_hub"
gr-nlp-toolkit = "@git+https://github.com/nlpaueb/gr-nlp-toolkit"
